version: "3.7"
services:
    frontend:
        build: ./frontend
        ports:
            - "${http__port}:80"
    api:
        build: ./server
        env_file: .env
        environment:
            http__port: 3000
        expose:
            - 3000
    updater:
        build: ./updater
        env_file: .env
        volumes:
            - ./logs:/var/log/tsrlogs/
    postgres:
        image: postgres
        env_file: .env
        environment:
            POSTGRES_USER: ${postgres__user}
            POSTGRES_PASSWORD: ${postgres__password}
            POSTGRES_DB: ${postgres__database}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: