version: "3.7"
services:
    frontend:
        build: ./frontend
        ports:
            - "3000:80"
    api:
        build: ./server
        env_file: .env
        environment:
            http__port: ${http__port}
        expose:
            - ${http__port}
    updater:
        build: ./updater
        env_file: .env
        volumes:
            - ./logs:/var/log/tsrlogs/
    installer:
      build: ./installer
      env_file: .env
      environment:
        files__bplan: /usr/src/data/reference/bplan/Geography_20200517_to_20201212_from_20191216.txt
      volumes:
        - ./reference:/usr/src/data/reference
      deploy:
        restart_policy: 
          condition: none
    postgres:
        image: postgres
        env_file: .env
        environment:
            POSTGRES_USER: ${postgres__user}
            POSTGRES_PASSWORD: ${postgres__password}
            POSTGRES_DB: ${postgres__database}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - pgdata:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080

volumes:
    pgdata: