version: "3.7"
services:
    app:
        build: ./server
        env_file: .env
        volumes:
            - ./client/build:/usr/src/app/client
        ports:
            - 127.0.0.1:${http__port}:${http__port}
    updater:
        build: ./updater
        env_file: .env
        volumes:
            - ./logs:/var/log/tsrlogs/
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: ${postgres__user}
            POSTGRES_PASSWORD: ${postgres__password}
            POSTGRES_DB: ${postgres__database}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: